/** Clerk appearance for embedded auth pages (header hidden — shell provides it) */
export const clerkAuthFormAppearance = {
  variables: {
    colorPrimary: '#00a36c',
    colorBackground: 'transparent',
    colorInputBackground: '#132238',
    colorInputText: '#f8fafc',
    colorText: '#f1f5f9',
    colorTextSecondary: '#cbd5e1',
    colorTextOnPrimaryBackground: '#0a1628',
    colorNeutral: '#475569',
    colorDanger: '#f87171',
    colorSuccess: '#34d399',
    colorWarning: '#fbbf24',
    borderRadius: '0.75rem',
    fontFamily: 'var(--font-outfit), system-ui, sans-serif',
    fontSize: '0.9375rem',
  },
  layout: {
    socialButtonsPlacement: 'top' as const,
    socialButtonsVariant: 'blockButton' as const,
  },
  elements: {
    rootBox: 'w-full mx-auto',
    cardBox: 'shadow-none w-full',
    card: 'bg-transparent shadow-none border-0 w-full p-0 gap-5',
    header: 'hidden',
    headerTitle: 'hidden',
    headerSubtitle: 'hidden',
    main: 'gap-4 w-full',
    socialButtons: 'w-full',
    socialButtonsBlockButton:
      'w-full border border-emerald-500/30 bg-[#132238] text-white hover:bg-emerald-500/10 hover:border-emerald-500/50 h-11',
    socialButtonsBlockButtonText: 'text-white font-medium',
    socialButtonsProviderIcon: 'opacity-100',
    dividerRow: 'my-2',
    dividerLine: 'bg-emerald-500/20',
    dividerText: 'text-slate-500 text-xs uppercase tracking-wider',
    formFieldLabel: 'text-slate-200 font-medium text-sm',
    formFieldInput:
      'border border-emerald-500/25 bg-[#132238] text-white placeholder:text-slate-500 h-11 focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400/30',
    formFieldHintText: 'text-slate-400',
    formFieldErrorText: 'text-red-400',
    formButtonPrimary:
      'w-full bg-[#00a36c] text-[#0a1628] font-bold hover:brightness-110 h-11 normal-case',
    formButtonReset: 'text-slate-300 hover:text-white',
    footer: 'bg-transparent pt-2',
    footerAction: 'justify-center',
    footerActionText: 'text-slate-400 text-sm',
    footerActionLink: 'text-emerald-400 font-semibold hover:text-emerald-300',
    footerPages: 'justify-center pt-3',
    footerPagesLink: 'text-slate-500 text-xs hover:text-emerald-400',
    identityPreviewText: 'text-slate-200',
    identityPreviewEditButton: 'text-emerald-400',
    alertText: 'text-slate-200',
    formFieldRow: 'w-full',
  },
};

export const clerkAppearance = {
  ...clerkAuthFormAppearance,
  variables: {
    ...clerkAuthFormAppearance.variables,
    colorBackground: '#0d2137',
  },
  elements: {
    ...clerkAuthFormAppearance.elements,
    header: undefined,
    headerTitle: 'text-white font-bold',
    headerSubtitle: 'text-slate-300',
    card: 'border border-emerald-500/20 bg-[#0d2137] shadow-2xl shadow-black/40 w-full',
    modalBackdrop: 'bg-black/70 backdrop-blur-sm',
    modalContent: 'border border-emerald-500/20 bg-[#0d2137]',
    userButtonPopoverCard: 'border border-emerald-500/20 bg-[#0d2137]',
    userPreviewMainIdentifier: 'text-white',
    userPreviewSecondaryIdentifier: 'text-slate-400',
    userButtonPopoverActionButton: 'text-slate-200 hover:bg-emerald-500/10',
    userButtonPopoverActionButtonText: 'text-slate-200',
    userButtonPopoverFooter: 'text-slate-500',
    navbarButton: 'text-slate-300 hover:text-white',
  },
};
