export const clerkAppearance = {
  variables: {
    colorPrimary: '#00a36c',
    colorBackground: '#0d2137',
    colorInputBackground: '#132238',
    colorInputText: '#f8fafc',
    colorText: '#f1f5f9',
    colorTextSecondary: '#cbd5e1',
    colorTextOnPrimaryBackground: '#0a1628',
    colorNeutral: '#475569',
    colorDanger: '#f87171',
    colorSuccess: '#34d399',
    colorWarning: '#fbbf24',
    borderRadius: '0.75rem',
    fontFamily: 'var(--font-outfit), system-ui, sans-serif',
    fontSize: '0.9375rem',
  },
  elements: {
    rootBox: 'w-full',
    card: 'border border-emerald-500/20 bg-[#0d2137] shadow-2xl shadow-black/40',
    cardBox: 'shadow-none',
    headerTitle: 'text-white font-bold',
    headerSubtitle: 'text-slate-300',
    main: 'gap-4',
    socialButtonsBlockButton:
      'border border-emerald-500/30 bg-[#132238] text-white hover:bg-emerald-500/10 hover:border-emerald-500/50',
    socialButtonsBlockButtonText: 'text-white font-medium',
    socialButtonsProviderIcon: 'opacity-100',
    dividerLine: 'bg-emerald-500/25',
    dividerText: 'text-slate-400 uppercase text-xs tracking-wider',
    formFieldLabel: 'text-slate-200 font-medium',
    formFieldInput:
      'border border-emerald-500/25 bg-[#132238] text-white placeholder:text-slate-400 focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400/30',
    formFieldHintText: 'text-slate-400',
    formFieldErrorText: 'text-red-400',
    formFieldSuccessText: 'text-emerald-400',
    formButtonPrimary:
      'bg-[#00a36c] text-[#0a1628] font-bold hover:brightness-110 shadow-glow',
    formButtonReset: 'text-slate-300 hover:text-white',
    footer: 'bg-transparent',
    footerActionText: 'text-slate-300',
    footerActionLink: 'text-emerald-400 font-semibold hover:text-emerald-300',
    footerPagesLink: 'text-slate-400 hover:text-emerald-400',
    identityPreviewText: 'text-slate-200',
    identityPreviewEditButton: 'text-emerald-400 hover:text-emerald-300',
    formHeaderTitle: 'text-white',
    formHeaderSubtitle: 'text-slate-300',
    alertText: 'text-slate-200',
    navbarButton: 'text-slate-300 hover:text-white',
    profileSectionTitle: 'text-slate-200',
    profileSectionContent: 'text-slate-300',
    modalBackdrop: 'bg-black/70 backdrop-blur-sm',
    modalContent: 'border border-emerald-500/20 bg-[#0d2137]',
    userButtonPopoverCard: 'border border-emerald-500/20 bg-[#0d2137]',
    userPreviewMainIdentifier: 'text-white',
    userPreviewSecondaryIdentifier: 'text-slate-400',
    userButtonPopoverActionButton: 'text-slate-200 hover:bg-emerald-500/10',
    userButtonPopoverActionButtonText: 'text-slate-200',
    userButtonPopoverFooter: 'text-slate-500',
  },
};
